title: "Matt Clements"
email: matt@mattclements.co.uk
description: "Web Developer from Milton Keynes"
#url: "http://localhost:4000"
url: "https://mattclements.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mattclementsuk
github_username:  mattclements
skype_username: clementsweb
google_analytics: UA-10215335-3

#auto: true
#server: true
exclude: ['README.md', 'sass/']

permalink: pretty

gems:
  - jekyll-feed
  - jekyll-compass
  - jekyll-sitemap
exclude:
  - Gemfile